I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 304, in script
    $andypoint -= 1
  File "game/script.rpy", line 304, in <module>
    $andypoint -= 1
NameError: name 'andypoint' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 304, in script
    $andypoint -= 1
  File "C:\Users\lisan\Downloads\renpy-8.0.1-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\lisan\Downloads\renpy-8.0.1-sdk\renpy\python.py", line 1049, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 304, in <module>
    $andypoint -= 1
NameError: name 'andypoint' is not defined

Windows-10-10.0.17763 AMD64
Ren'Py 8.0.1.22070801
The Henhouse 1.0
Thu Oct  6 12:12:35 2022
