I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 116, in script
    if error:
  File "game/script.rpy", line 116, in <module>
    if error:
NameError: name 'error' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 116, in script
    if error:
  File "C:\Users\lisan\Downloads\renpy-8.0.1-sdk\renpy\ast.py", line 2115, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\lisan\Downloads\renpy-8.0.1-sdk\renpy\python.py", line 1080, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\lisan\Downloads\renpy-8.0.1-sdk\renpy\python.py", line 1073, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 116, in <module>
    if error:
NameError: name 'error' is not defined

Windows-10-10.0.17763 AMD64
Ren'Py 8.0.1.22070801
The Henhouse 1.0
Mon Oct  3 12:10:17 2022
